version: "3.7"

services:
  mobifone_backend:
    container_name: mobifone_backend
    build: mobifone_backend
    working_dir: /src/app
    ports:
      - 3400:3400
    volumes:
      - ./mobifone_backend:/src/app
      - /src/app/node_modules
    networks:
        - mobifone
  free_mobifone:
    container_name: free_mobifone
    build: free_mobifone
    working_dir: /src/app
    ports:
      - 3600:3600
    volumes:
      - ./free_mobifone:/src/app
      - /src/app/node_modules
    networks:
      - mobifone
  mobifone-frontend-gateway:
    networks:
      - mobifone
    build:
      context: ./mobifone-frontend-gateway
    image: mobifone-frontend-gateway-image
    container_name: mobifone-frontend-gateway-container
    ports:
      - '1996:1996'
    volumes:
      - './mobifone-frontend-gateway/mobifone-frontend.conf:/etc/nginx/conf.d/mobifone-frontend.conf'
      - './mobifone-frontend-gateway/log:/var/log/nginx'
    links:
      - mobifone_backend
    depends_on:
      - mobifone_backend
    command:
      - /wait-for-it.sh
      - 'mobifone-frontend:1996'
      - '--'
      - nginx
      - '-g'
      - daemon off;
networks:
  mobifone:
        
